-- maeosan · complete database schema (generated by `npm run db:bundle`, do not edit)
-- Supabase → SQL Editor → New query → paste this whole file → Run.
-- On a project that already has other tables, run supabase/reset.sql first.

notify pgrst, 'reload schema';

-- ═══════════════════════════════════════════════════════════════════════════
-- 20260913000100_core_schema.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────────────
-- maeosan · 01 · core schema
-- Profiles, workspaces, membership, invitations, conversations and messages.
-- ─────────────────────────────────────────────────────────────────────────────

create extension if not exists pgcrypto with schema extensions;
create extension if not exists pg_trgm with schema extensions;

-- Enums ──────────────────────────────────────────────────────────────────────

create type public.workspace_role as enum ('owner', 'admin', 'member');
create type public.invitation_status as enum ('pending', 'accepted', 'revoked');
create type public.conversation_kind as enum ('direct', 'group');
create type public.message_kind as enum ('text', 'system');

-- Shared trigger: keep updated_at honest ─────────────────────────────────────

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- Profiles ───────────────────────────────────────────────────────────────────
-- One row per auth user. Created by trigger, never inserted by clients.

create table public.profiles (
  id            uuid primary key references auth.users (id) on delete cascade,
  email         text not null default '',
  full_name     text check (full_name is null or char_length(full_name) between 1 and 80),
  display_name  text check (display_name is null or char_length(display_name) between 1 and 40),
  title         text check (title is null or char_length(title) <= 80),
  status_text   text check (status_text is null or char_length(status_text) <= 100),
  avatar_path   text check (avatar_path is null or split_part(avatar_path, '/', 1) = id::text),
  color         text not null default 'cobalt'
                check (color in ('tomato', 'saffron', 'grass', 'lagoon', 'cobalt', 'iris', 'bubblegum', 'clay')),
  onboarded_at  timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index profiles_email_idx on public.profiles (email);

create trigger profiles_touch_updated_at
  before update on public.profiles
  for each row execute function public.touch_updated_at();

-- Workspaces ─────────────────────────────────────────────────────────────────

create table public.workspaces (
  id                  uuid primary key default gen_random_uuid(),
  name                text not null check (char_length(btrim(name)) between 2 and 60),
  slug                text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{1,38}[a-z0-9]$'),
  team_size           text check (team_size is null or team_size in ('solo', '2-10', '11-50', '51-200', '200+')),
  use_case            text check (use_case is null or char_length(use_case) <= 40),
  members_can_invite  boolean not null default true,
  created_by          uuid references public.profiles (id) on delete set null,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index workspaces_created_by_idx on public.workspaces (created_by, created_at desc);

create trigger workspaces_touch_updated_at
  before update on public.workspaces
  for each row execute function public.touch_updated_at();

create table public.workspace_members (
  workspace_id  uuid not null references public.workspaces (id) on delete cascade,
  user_id       uuid not null references public.profiles (id) on delete cascade,
  role          public.workspace_role not null default 'member',
  joined_at     timestamptz not null default now(),
  primary key (workspace_id, user_id)
);

create index workspace_members_user_idx on public.workspace_members (user_id);

-- Invitations ────────────────────────────────────────────────────────────────

create table public.invitations (
  id            uuid primary key default gen_random_uuid(),
  workspace_id  uuid not null references public.workspaces (id) on delete cascade,
  email         text not null check (email = lower(email) and email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  role          public.workspace_role not null default 'member' check (role <> 'owner'),
  token         text not null unique default encode(extensions.gen_random_bytes(24), 'hex'),
  status        public.invitation_status not null default 'pending',
  invited_by    uuid references public.profiles (id) on delete set null,
  accepted_by   uuid references public.profiles (id) on delete set null,
  expires_at    timestamptz not null default (now() + interval '14 days'),
  accepted_at   timestamptz,
  created_at    timestamptz not null default now()
);

create unique index invitations_one_pending_per_email
  on public.invitations (workspace_id, email) where status = 'pending';
create index invitations_pending_email_idx
  on public.invitations (email) where status = 'pending';
create index invitations_workspace_created_idx
  on public.invitations (workspace_id, created_at desc);

-- Conversations ──────────────────────────────────────────────────────────────
-- No channels, no threads: a conversation is either a 1:1 or a small group.

create table public.conversations (
  id               uuid primary key default gen_random_uuid(),
  workspace_id     uuid not null references public.workspaces (id) on delete cascade,
  kind             public.conversation_kind not null,
  name             text check (name is null or char_length(btrim(name)) between 1 and 80),
  direct_key       text unique,
  created_by       uuid references public.profiles (id) on delete set null,
  last_message_at  timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  constraint conversations_direct_key_matches_kind check ((kind = 'direct') = (direct_key is not null)),
  constraint conversations_direct_has_no_name check (kind = 'group' or name is null)
);

create index conversations_workspace_activity_idx
  on public.conversations (workspace_id, last_message_at desc nulls last);

create trigger conversations_touch_updated_at
  before update on public.conversations
  for each row execute function public.touch_updated_at();

create table public.conversation_participants (
  conversation_id  uuid not null references public.conversations (id) on delete cascade,
  user_id          uuid not null references public.profiles (id) on delete cascade,
  joined_at        timestamptz not null default now(),
  last_read_at     timestamptz not null default now(),
  muted            boolean not null default false,
  primary key (conversation_id, user_id)
);

create index conversation_participants_user_idx on public.conversation_participants (user_id);

-- Messages ───────────────────────────────────────────────────────────────────
-- ids are generated by the client so optimistic sends reconcile exactly.

create table public.messages (
  id               uuid primary key default gen_random_uuid(),
  conversation_id  uuid not null references public.conversations (id) on delete cascade,
  sender_id        uuid references public.profiles (id) on delete set null,
  kind             public.message_kind not null default 'text',
  body             text not null default '' check (char_length(body) <= 4000),
  attachments      jsonb not null default '[]'::jsonb
                   check (jsonb_typeof(attachments) = 'array' and jsonb_array_length(attachments) <= 10),
  meta             jsonb not null default '{}'::jsonb check (jsonb_typeof(meta) = 'object'),
  reply_to_id      uuid references public.messages (id) on delete set null,
  edited_at        timestamptz,
  deleted_at       timestamptz,
  created_at       timestamptz not null default now(),
  constraint messages_has_content check (
    deleted_at is not null
    or kind = 'system'
    or char_length(btrim(body)) > 0
    or jsonb_array_length(attachments) > 0
  )
);

create index messages_conversation_timeline_idx
  on public.messages (conversation_id, created_at desc, id desc);
create index messages_body_search_idx
  on public.messages using gin (body extensions.gin_trgm_ops);

create table public.message_reactions (
  message_id       uuid not null references public.messages (id) on delete cascade,
  user_id          uuid not null references public.profiles (id) on delete cascade,
  conversation_id  uuid not null references public.conversations (id) on delete cascade,
  emoji            text not null check (char_length(emoji) between 1 and 16),
  created_at       timestamptz not null default now(),
  primary key (message_id, user_id, emoji)
);

create index message_reactions_conversation_idx on public.message_reactions (conversation_id);

-- ═══════════════════════════════════════════════════════════════════════════
-- 20260913000200_functions.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────────────
-- maeosan · 02 · integrity triggers and RPC API
-- Every write that touches more than one row goes through a function here, so
-- it is atomic and authorised in exactly one place.
-- ─────────────────────────────────────────────────────────────────────────────

-- Access helpers ─────────────────────────────────────────────────────────────
-- SECURITY DEFINER so policies can call them without recursing into RLS.

create or replace function public.is_workspace_member(p_workspace_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.workspace_members m
    where m.workspace_id = p_workspace_id
      and m.user_id = (select auth.uid())
  );
$$;

create or replace function public.is_workspace_admin(p_workspace_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.workspace_members m
    where m.workspace_id = p_workspace_id
      and m.user_id = (select auth.uid())
      and m.role in ('owner', 'admin')
  );
$$;

create or replace function public.is_conversation_participant(p_conversation_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.conversation_participants cp
    where cp.conversation_id = p_conversation_id
      and cp.user_id = (select auth.uid())
  );
$$;

create or replace function public.shares_workspace_with(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.workspace_members mine
    join public.workspace_members theirs on theirs.workspace_id = mine.workspace_id
    where mine.user_id = (select auth.uid())
      and theirs.user_id = p_user_id
  );
$$;

create or replace function public.require_user()
returns uuid
language plpgsql
stable
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'You need to be signed in.' using errcode = '28000';
  end if;
  return v_uid;
end;
$$;

-- Auth → profile sync ────────────────────────────────────────────────────────

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_palette text[] := array['tomato', 'saffron', 'grass', 'lagoon', 'cobalt', 'iris', 'bubblegum', 'clay'];
  v_name text := nullif(btrim(coalesce(
    new.raw_user_meta_data ->> 'full_name',
    new.raw_user_meta_data ->> 'name',
    ''
  )), '');
begin
  insert into public.profiles (id, email, full_name, color)
  values (
    new.id,
    lower(coalesce(new.email, '')),
    left(v_name, 80),
    v_palette[1 + floor(random() * array_length(v_palette, 1))::int]
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.handle_user_email_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.profiles
     set email = lower(coalesce(new.email, ''))
   where id = new.id;
  return new;
end;
$$;

drop trigger if exists on_auth_user_email_changed on auth.users;
create trigger on_auth_user_email_changed
  after update of email on auth.users
  for each row
  when (old.email is distinct from new.email)
  execute function public.handle_user_email_change();

-- Accounts created before this schema was installed get a profile as well.
insert into public.profiles (id, email)
select u.id, lower(coalesce(u.email, ''))
from auth.users u
on conflict (id) do nothing;

-- Message integrity ──────────────────────────────────────────────────────────
-- Clients may only write body/attachments/reply target on insert and body or a
-- soft delete on update. Everything else is pinned here.

create or replace function public.messages_before_write()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_attachment jsonb;
  v_prefix text;
begin
  if tg_op = 'INSERT' then
    new.created_at := now();
    new.edited_at := null;
    new.deleted_at := null;
    new.body := btrim(new.body, E' \t\r\n');

    if new.reply_to_id is not null and not exists (
      select 1 from public.messages r
      where r.id = new.reply_to_id and r.conversation_id = new.conversation_id
    ) then
      raise exception 'You can only reply to messages in the same conversation.' using errcode = '22023';
    end if;

    if new.kind = 'text' then
      v_prefix := new.conversation_id::text || '/' || new.sender_id::text || '/';
      for v_attachment in select value from jsonb_array_elements(new.attachments) loop
        if jsonb_typeof(v_attachment) <> 'object'
          or left(coalesce(v_attachment ->> 'path', ''), length(v_prefix)) <> v_prefix
          or coalesce(v_attachment ->> 'name', '') = ''
        then
          raise exception 'One of the attachments is invalid.' using errcode = '22023';
        end if;
      end loop;
    end if;

    return new;
  end if;

  -- Only foreign keys (ON DELETE SET NULL for a deleted account or message)
  -- change these columns; clients hold no privilege on them.
  if new.sender_id is distinct from old.sender_id or new.reply_to_id is distinct from old.reply_to_id then
    return new;
  end if;

  if old.deleted_at is not null then
    raise exception 'This message was deleted.' using errcode = '22023';
  end if;

  new.id := old.id;
  new.conversation_id := old.conversation_id;
  new.sender_id := old.sender_id;
  new.kind := old.kind;
  new.meta := old.meta;
  new.reply_to_id := old.reply_to_id;
  new.created_at := old.created_at;

  if new.deleted_at is not null then
    new.deleted_at := now();
    new.body := '';
    new.attachments := '[]'::jsonb;
    new.edited_at := old.edited_at;
    return new;
  end if;

  new.attachments := old.attachments;
  if new.body is distinct from old.body then
    new.body := btrim(new.body, E' \t\r\n');
    new.edited_at := now();
  else
    new.edited_at := old.edited_at;
  end if;

  return new;
end;
$$;

create trigger messages_before_write
  before insert or update on public.messages
  for each row execute function public.messages_before_write();

create or replace function public.messages_after_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.conversations c
     set last_message_at = new.created_at
   where c.id = new.conversation_id
     and (c.last_message_at is null or c.last_message_at < new.created_at);
  return null;
end;
$$;

create trigger messages_after_insert
  after insert on public.messages
  for each row execute function public.messages_after_insert();

create or replace function public.message_reactions_before_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  select m.conversation_id
    into new.conversation_id
    from public.messages m
   where m.id = new.message_id
     and m.kind = 'text'
     and m.deleted_at is null;

  if new.conversation_id is null then
    raise exception 'That message no longer exists.' using errcode = '22023';
  end if;

  new.created_at := now();
  return new;
end;
$$;

create trigger message_reactions_before_insert
  before insert on public.message_reactions
  for each row execute function public.message_reactions_before_insert();

-- Internal: system messages (group created, people added, renamed …) ─────────

create or replace function public.post_system_message(
  p_conversation_id uuid,
  p_actor uuid,
  p_event text,
  p_meta jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.messages (conversation_id, sender_id, kind, body, meta)
  values (
    p_conversation_id,
    p_actor,
    'system',
    '',
    jsonb_build_object('event', p_event) || coalesce(p_meta, '{}'::jsonb)
  );
end;
$$;

revoke execute on function public.post_system_message(uuid, uuid, text, jsonb) from public, anon, authenticated;

-- Workspaces ─────────────────────────────────────────────────────────────────

create or replace function public.is_workspace_slug_available(p_slug text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(p_slug, '') ~ '^[a-z0-9][a-z0-9-]{1,38}[a-z0-9]$'
     and not exists (select 1 from public.workspaces w where w.slug = p_slug);
$$;

create or replace function public.create_workspace(
  p_name text,
  p_slug text,
  p_team_size text default null,
  p_use_case text default null
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := public.require_user();
  v_id uuid;
  v_slug text := lower(btrim(coalesce(p_slug, '')));
begin
  if (
    select count(*) from public.workspaces w
    where w.created_by = v_uid and w.created_at > now() - interval '1 day'
  ) >= 5 then
    raise exception 'You have created a lot of workspaces today. Try again tomorrow.' using errcode = 'P0001';
  end if;

  begin
    insert into public.workspaces (name, slug, team_size, use_case, created_by)
    values (btrim(p_name), v_slug, p_team_size, nullif(btrim(coalesce(p_use_case, '')), ''), v_uid)
    returning id into v_id;
  exception
    when unique_violation then
      raise exception 'That workspace URL is already taken.' using errcode = '23505';
  end;

  insert into public.workspace_members (workspace_id, user_id, role)
  values (v_id, v_uid, 'owner');

  return v_slug;
end;
$$;

create or replace function public.my_workspaces()
returns table (
  id uuid,
  name text,
  slug text,
  role public.workspace_role,
  joined_at timestamptz,
  member_count integer
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    w.id,
    w.name,
    w.slug,
    m.role,
    m.joined_at,
    (select count(*)::int from public.workspace_members x where x.workspace_id = w.id)
  from public.workspace_members m
  join public.workspaces w on w.id = m.workspace_id
  where m.user_id = (select auth.uid())
  order by m.joined_at;
$$;

create or replace function public.list_workspace_members(
  p_workspace_id uuid,
  p_user_id uuid default null
)
returns table (
  user_id uuid,
  role public.workspace_role,
  joined_at timestamptz,
  email text,
  full_name text,
  display_name text,
  title text,
  status_text text,
  avatar_path text,
  color text
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    m.user_id,
    m.role,
    m.joined_at,
    p.email,
    p.full_name,
    p.display_name,
    p.title,
    p.status_text,
    p.avatar_path,
    p.color
  from public.workspace_members m
  join public.profiles p on p.id = m.user_id
  where m.workspace_id = p_workspace_id
    and (p_user_id is null or m.user_id = p_user_id)
    and (select public.is_workspace_member(p_workspace_id))
  order by lower(coalesce(p.display_name, p.full_name, p.email));
$$;

create or replace function public.update_member_role(
  p_workspace_id uuid,
  p_user_id uuid,
  p_role public.workspace_role
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := public.require_user();
  v_actor public.workspace_role;
  v_target public.workspace_role;
begin
  if p_role not in ('admin', 'member') then
    raise exception 'Choose admin or member.' using errcode = '22023';
  end if;

  select m.role into v_actor from public.workspace_members m
   where m.workspace_id = p_workspace_id and m.user_id = v_uid;
  select m.role into v_target from public.workspace_members m
   where m.workspace_id = p_workspace_id and m.user_id = p_user_id;

  if v_actor is null or v_actor = 'member' then
    raise exception 'Only admins can change roles.' using errcode = '42501';
  end if;
  if v_target is null then
    raise exception 'That person is not in this workspace.' using errcode = '22023';
  end if;
  if v_target = 'owner' then
    raise exception 'The owner''s role can''t be changed. Transfer ownership instead.' using errcode = '22023';
  end if;
  if p_user_id = v_uid then
    raise exception 'You can''t change your own role.' using errcode = '22023';
  end if;

  update public.workspace_members m
     set role = p_role
   where m.workspace_id = p_workspace_id and m.user_id = p_user_id;
end;
$$;

create or replace function public.remove_workspace_member(p_workspace_id uuid, p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := public.require_user();
  v_actor public.workspace_role;
  v_target public.workspace_role;
  v_conversation uuid;
begin
  select m.role into v_actor from public.workspace_members m
   where m.workspace_id = p_workspace_id and m.user_id = v_uid;
  select m.role into v_target from public.workspace_members m
   where m.workspace_id = p_workspace_id and m.user_id = p_user_id;

  if v_actor is null or v_target is null then
    raise exception 'That person is not in this workspace.' using errcode = '22023';
  end if;
  if v_target = 'owner' then
    raise exception 'The owner can''t leave or be removed. Transfer ownership first.' using errcode = '22023';
  end if;
  if p_user_id <> v_uid then
    if v_actor = 'member' then
      raise exception 'Only admins can remove people.' using errcode = '42501';
    end if;
    if v_actor = 'admin' and v_target = 'admin' then
      raise exception 'Only the owner can remove an admin.' using errcode = '42501';
    end if;
  end if;

  for v_conversation in
    select cp.conversation_id
    from public.conversation_participants cp
    join public.conversations c on c.id = cp.conversation_id
    where cp.user_id = p_user_id
      and c.workspace_id = p_workspace_id
      and c.kind = 'group'
  loop
    delete from public.conversation_participants cp
     where cp.conversation_id = v_conversation and cp.user_id = p_user_id;
    perform public.post_system_message(v_conversation, p_user_id, 'member_left');
  end loop;

  delete from public.conversation_participants cp
   using public.conversations c
   where c.id = cp.conversation_id
     and c.workspace_id = p_workspace_id
     and cp.user_id = p_user_id;

  delete from public.workspace_members m
   where m.workspace_id = p_workspace_id and m.user_id = p_user_id;
end;
$$;

create or replace function public.transfer_workspace_ownership(p_workspace_id uuid, p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := public.require_user();
begin
  if not exists (
    select 1 from public.workspace_members m
    where m.workspace_id = p_workspace_id and m.user_id = v_uid and m.role = 'owner'
  ) then
    raise exception 'Only the owner can transfer ownership.' using errcode = '42501';
  end if;
  if p_user_id = v_uid then
    raise exception 'You already own this workspace.' using errcode = '22023';
  end if;
  if not exists (
    select 1 from public.workspace_members m
    where m.workspace_id = p_workspace_id and m.user_id = p_user_id
  ) then
    raise exception 'That person is not in this workspace.' using errcode = '22023';
  end if;

  update public.workspace_members m set role = 'admin'
   where m.workspace_id = p_workspace_id and m.user_id = v_uid;
  update public.workspace_members m set role = 'owner'
   where m.workspace_id = p_workspace_id and m.user_id = p_user_id;
end;
$$;

create or replace function public.delete_workspace(p_workspace_id uuid, p_confirm_slug text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := public.require_user();
  v_slug text;
begin
  select w.slug into v_slug
  from public.workspaces w
  join public.workspace_members m on m.workspace_id = w.id
  where w.id = p_workspace_id and m.user_id = v_uid and m.role = 'owner';

  if v_slug is null then
    raise exception 'Only the owner can delete this workspace.' using errcode = '42501';
  end if;
  if v_slug <> coalesce(p_confirm_slug, '') then
    raise exception 'Type the workspace URL exactly to confirm.' using errcode = '22023';
  end if;

  delete from public.workspaces w where w.id = p_workspace_id;
end;
$$;

-- Removes workspaces the caller owns alone and refuses when others depend on
-- them. The auth user itself is deleted by the server with the service role.
create or replace function public.prepare_account_deletion()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := public.require_user();
  v_blocking text;
begin
  select string_agg(w.name, ', ')
    into v_blocking
    from public.workspace_members m
    join public.workspaces w on w.id = m.workspace_id
   where m.user_id = v_uid
     and m.role = 'owner'
     and exists (
       select 1 from public.workspace_members o
       where o.workspace_id = m.workspace_id and o.user_id <> v_uid
     );

  if v_blocking is not null then
    raise exception 'Transfer ownership of % before deleting your account.', v_blocking using errcode = '22023';
  end if;

  delete from public.workspaces w
   where w.id in (
     select m.workspace_id from public.workspace_members m
     where m.user_id = v_uid and m.role = 'owner'
   );
end;
$$;

-- Invitations ────────────────────────────────────────────────────────────────

create or replace function public.invite_workspace_members(
  p_workspace_id uuid,
  p_emails text[],
  p_role public.workspace_role default 'member'
)
returns table (invited_email text, invite_token text, outcome text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := public.require_user();
  v_membership record;
  v_role public.workspace_role;
  v_members_can_invite boolean;
  v_email text;
  v_count integer := coalesce(array_length(p_emails, 1), 0);
  v_recent integer;
begin
  select m.role, w.members_can_invite
    into v_membership
    from public.workspace_members m
    join public.workspaces w on w.id = m.workspace_id
   where m.workspace_id = p_workspace_id and m.user_id = v_uid;

  if not found then
    raise exception 'Workspace not found.' using errcode = '42501';
  end if;
  v_role := v_membership.role;
  v_members_can_invite := v_membership.members_can_invite;
  if v_role = 'member' and not v_members_can_invite then
    raise exception 'Only admins can invite people to this workspace.' using errcode = '42501';
  end if;
  if p_role = 'owner' or (p_role = 'admin' and v_role = 'member') then
    raise exception 'You can''t invite people with that role.' using errcode = '42501';
  end if;
  if v_count = 0 then
    return;
  end if;
  if v_count > 25 then
    raise exception 'You can invite up to 25 people at a time.' using errcode = '22023';
  end if;

  select count(*) into v_recent
    from public.invitations i
   where i.workspace_id = p_workspace_id and i.created_at > now() - interval '1 hour';
  if v_recent + v_count > 100 then
    raise exception 'That''s a lot of invitations in an hour. Try again a little later.' using errcode = 'P0001';
  end if;

  for v_email in
    select distinct lower(btrim(e)) from unnest(p_emails) as e where btrim(coalesce(e, '')) <> ''
  loop
    invited_email := v_email;
    invite_token := null;

    if v_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
      outcome := 'invalid';
      return next;
      continue;
    end if;

    if exists (
      select 1 from public.workspace_members m
      join public.profiles p on p.id = m.user_id
      where m.workspace_id = p_workspace_id and p.email = v_email
    ) then
      outcome := 'already_member';
      return next;
      continue;
    end if;

    update public.invitations i
       set expires_at = now() + interval '14 days',
           role = p_role,
           invited_by = v_uid
     where i.workspace_id = p_workspace_id
       and i.email = v_email
       and i.status = 'pending'
    returning i.token into invite_token;

    if found then
      outcome := 'resent';
      return next;
      continue;
    end if;

    insert into public.invitations as i (workspace_id, email, role, invited_by)
    values (p_workspace_id, v_email, p_role, v_uid)
    returning i.token into invite_token;

    outcome := 'invited';
    return next;
  end loop;
end;
$$;

create or replace function public.get_invitation(p_token text)
returns table (
  workspace_id uuid,
  workspace_name text,
  workspace_slug text,
  email text,
  role public.workspace_role,
  status text,
  expires_at timestamptz,
  inviter_name text
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    w.id,
    w.name,
    w.slug,
    i.email,
    i.role,
    case
      when i.status = 'pending' and i.expires_at < now() then 'expired'
      else i.status::text
    end,
    i.expires_at,
    coalesce(p.display_name, p.full_name, 'A teammate')
  from public.invitations i
  join public.workspaces w on w.id = i.workspace_id
  left join public.profiles p on p.id = i.invited_by
  where i.token = p_token;
$$;

create or replace function public.my_pending_invitations()
returns table (
  token text,
  workspace_id uuid,
  workspace_name text,
  workspace_slug text,
  role public.workspace_role,
  inviter_name text,
  member_count integer,
  created_at timestamptz,
  expires_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    i.token,
    w.id,
    w.name,
    w.slug,
    i.role,
    coalesce(p.display_name, p.full_name, 'A teammate'),
    (select count(*)::int from public.workspace_members x where x.workspace_id = w.id),
    i.created_at,
    i.expires_at
  from public.invitations i
  join public.workspaces w on w.id = i.workspace_id
  left join public.profiles p on p.id = i.invited_by
  where i.status = 'pending'
    and i.expires_at > now()
    and i.email = (select lower(u.email) from auth.users u where u.id = (select auth.uid()))
    and not exists (
      select 1 from public.workspace_members m
      where m.workspace_id = i.workspace_id and m.user_id = (select auth.uid())
    )
  order by i.created_at desc;
$$;

create or replace function public.accept_invitation(p_token text)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := public.require_user();
  v_email text;
  v_confirmed timestamptz;
  v_invite public.invitations%rowtype;
  v_slug text;
begin
  select lower(u.email), u.email_confirmed_at
    into v_email, v_confirmed
    from auth.users u
   where u.id = v_uid;

  select * into v_invite
    from public.invitations i
   where i.token = p_token
   for update;

  if not found then
    raise exception 'This invitation link is not valid.' using errcode = '22023';
  end if;

  select w.slug into v_slug from public.workspaces w where w.id = v_invite.workspace_id;

  if v_invite.status = 'accepted' then
    if v_invite.accepted_by = v_uid then
      return v_slug;
    end if;
    raise exception 'This invitation has already been used.' using errcode = '22023';
  end if;
  if v_invite.status = 'revoked' then
    raise exception 'This invitation was cancelled.' using errcode = '22023';
  end if;
  if v_invite.expires_at < now() then
    raise exception 'This invitation has expired. Ask for a new one.' using errcode = '22023';
  end if;
  if v_invite.email <> v_email then
    raise exception 'This invitation was sent to a different email address.' using errcode = '42501';
  end if;
  if v_confirmed is null then
    raise exception 'Confirm your email address before joining.' using errcode = '42501';
  end if;

  insert into public.workspace_members (workspace_id, user_id, role)
  values (v_invite.workspace_id, v_uid, v_invite.role)
  on conflict (workspace_id, user_id) do nothing;

  update public.invitations i
     set status = 'accepted', accepted_by = v_uid, accepted_at = now()
   where i.id = v_invite.id;

  return v_slug;
end;
$$;

create or replace function public.decline_invitation(p_token text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := public.require_user();
begin
  update public.invitations i
     set status = 'revoked'
   where i.token = p_token
     and i.status = 'pending'
     and i.email = (select lower(u.email) from auth.users u where u.id = v_uid);
end;
$$;

create or replace function public.revoke_invitation(p_invitation_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := public.require_user();
begin
  update public.invitations i
     set status = 'revoked'
   where i.id = p_invitation_id
     and i.status = 'pending'
     and (i.invited_by = v_uid or public.is_workspace_admin(i.workspace_id));

  if not found then
    raise exception 'Invitation not found.' using errcode = '22023';
  end if;
end;
$$;

-- Conversations ──────────────────────────────────────────────────────────────

create or replace function public.list_conversations(
  p_workspace_id uuid,
  p_conversation_id uuid default null
)
returns table (
  id uuid,
  kind public.conversation_kind,
  name text,
  created_by uuid,
  created_at timestamptz,
  last_message_at timestamptz,
  muted boolean,
  last_read_at timestamptz,
  unread_count integer,
  participants jsonb,
  last_message jsonb
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    c.id,
    c.kind,
    c.name,
    c.created_by,
    c.created_at,
    c.last_message_at,
    me.muted,
    me.last_read_at,
    unread.total::int,
    roster.participants,
    latest.message
  from public.conversation_participants me
  join public.conversations c on c.id = me.conversation_id
  cross join lateral (
    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'user_id', cp.user_id,
          'joined_at', cp.joined_at,
          'last_read_at', cp.last_read_at
        )
        order by cp.joined_at
      ),
      '[]'::jsonb
    ) as participants
    from public.conversation_participants cp
    where cp.conversation_id = c.id
  ) roster
  left join lateral (
    select jsonb_build_object(
      'id', m.id,
      'sender_id', m.sender_id,
      'kind', m.kind,
      'body', left(m.body, 180),
      'meta', m.meta,
      'attachment_count', jsonb_array_length(m.attachments),
      'deleted_at', m.deleted_at,
      'created_at', m.created_at
    ) as message
    from public.messages m
    where m.conversation_id = c.id
    order by m.created_at desc, m.id desc
    limit 1
  ) latest on true
  cross join lateral (
    select count(*) as total
    from (
      select 1
      from public.messages m
      where m.conversation_id = c.id
        and m.created_at > me.last_read_at
        and m.kind = 'text'
        and m.deleted_at is null
        and m.sender_id is distinct from me.user_id
      limit 100
    ) capped
  ) unread
  where me.user_id = (select auth.uid())
    and c.workspace_id = p_workspace_id
    and (
      (p_conversation_id is not null and c.id = p_conversation_id)
      or (p_conversation_id is null and (c.last_message_at is not null or c.created_by = me.user_id))
    )
  order by coalesce(c.last_message_at, c.created_at) desc;
$$;

create or replace function public.create_direct_conversation(p_workspace_id uuid, p_user_id uuid)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := public.require_user();
  v_key text;
  v_id uuid;
begin
  if p_user_id = v_uid then
    raise exception 'Pick someone other than yourself.' using errcode = '22023';
  end if;
  if not public.is_workspace_member(p_workspace_id) or not exists (
    select 1 from public.workspace_members m
    where m.workspace_id = p_workspace_id and m.user_id = p_user_id
  ) then
    raise exception 'That person is not in this workspace.' using errcode = '22023';
  end if;

  v_key := p_workspace_id::text || ':' || least(v_uid, p_user_id)::text || ':' || greatest(v_uid, p_user_id)::text;

  insert into public.conversations (workspace_id, kind, direct_key, created_by)
  values (p_workspace_id, 'direct', v_key, v_uid)
  on conflict (direct_key) do nothing
  returning id into v_id;

  if v_id is null then
    select c.id into v_id from public.conversations c where c.direct_key = v_key;
  end if;

  insert into public.conversation_participants (conversation_id, user_id)
  values (v_id, v_uid), (v_id, p_user_id)
  on conflict (conversation_id, user_id) do nothing;

  return v_id;
end;
$$;

create or replace function public.create_group_conversation(
  p_workspace_id uuid,
  p_member_ids uuid[],
  p_name text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := public.require_user();
  v_members uuid[];
  v_name text := nullif(btrim(coalesce(p_name, '')), '');
  v_id uuid;
begin
  if not public.is_workspace_member(p_workspace_id) then
    raise exception 'Workspace not found.' using errcode = '42501';
  end if;

  select coalesce(array_agg(distinct x), '{}')
    into v_members
    from unnest(coalesce(p_member_ids, '{}'::uuid[])) as x
   where x <> v_uid;

  if coalesce(array_length(v_members, 1), 0) = 0 then
    raise exception 'Pick at least one person.' using errcode = '22023';
  end if;
  if array_length(v_members, 1) > 99 then
    raise exception 'Group chats can have up to 100 people.' using errcode = '22023';
  end if;
  if exists (
    select 1 from unnest(v_members) as x
    where not exists (
      select 1 from public.workspace_members m
      where m.workspace_id = p_workspace_id and m.user_id = x
    )
  ) then
    raise exception 'Some of those people are not in this workspace.' using errcode = '22023';
  end if;

  insert into public.conversations (workspace_id, kind, name, created_by)
  values (p_workspace_id, 'group', v_name, v_uid)
  returning id into v_id;

  insert into public.conversation_participants (conversation_id, user_id)
  select v_id, x from unnest(array_append(v_members, v_uid)) as x;

  perform public.post_system_message(v_id, v_uid, 'group_created', jsonb_build_object('name', v_name));
  return v_id;
end;
$$;

create or replace function public.add_conversation_participants(p_conversation_id uuid, p_user_ids uuid[])
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := public.require_user();
  v_conversation public.conversations%rowtype;
  v_existing uuid[];
  v_new uuid[];
begin
  select * into v_conversation from public.conversations c where c.id = p_conversation_id;
  if not found or not public.is_conversation_participant(p_conversation_id) then
    raise exception 'Conversation not found.' using errcode = '42501';
  end if;

  select coalesce(array_agg(cp.user_id), '{}')
    into v_existing
    from public.conversation_participants cp
   where cp.conversation_id = p_conversation_id;

  select coalesce(array_agg(distinct x), '{}')
    into v_new
    from unnest(coalesce(p_user_ids, '{}'::uuid[])) as x
   where not (x = any (v_existing));

  if coalesce(array_length(v_new, 1), 0) = 0 then
    return p_conversation_id;
  end if;

  if exists (
    select 1 from unnest(v_new) as x
    where not exists (
      select 1 from public.workspace_members m
      where m.workspace_id = v_conversation.workspace_id and m.user_id = x
    )
  ) then
    raise exception 'Some of those people are not in this workspace.' using errcode = '22023';
  end if;

  -- A 1:1 stays private: adding people starts a fresh group instead.
  if v_conversation.kind = 'direct' then
    return public.create_group_conversation(v_conversation.workspace_id, v_existing || v_new, null);
  end if;

  if array_length(v_existing, 1) + array_length(v_new, 1) > 100 then
    raise exception 'Group chats can have up to 100 people.' using errcode = '22023';
  end if;

  insert into public.conversation_participants (conversation_id, user_id)
  select p_conversation_id, x from unnest(v_new) as x;

  perform public.post_system_message(
    p_conversation_id, v_uid, 'members_added', jsonb_build_object('user_ids', to_jsonb(v_new))
  );
  return p_conversation_id;
end;
$$;

create or replace function public.leave_conversation(p_conversation_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := public.require_user();
begin
  if not exists (
    select 1 from public.conversations c
    join public.conversation_participants cp on cp.conversation_id = c.id
    where c.id = p_conversation_id and c.kind = 'group' and cp.user_id = v_uid
  ) then
    raise exception 'You can only leave group chats you are part of.' using errcode = '22023';
  end if;

  delete from public.conversation_participants cp
   where cp.conversation_id = p_conversation_id and cp.user_id = v_uid;

  perform public.post_system_message(p_conversation_id, v_uid, 'member_left');
end;
$$;

create or replace function public.rename_conversation(p_conversation_id uuid, p_name text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := public.require_user();
  v_name text := nullif(btrim(coalesce(p_name, '')), '');
begin
  if v_name is not null and char_length(v_name) > 80 then
    raise exception 'Keep the name under 80 characters.' using errcode = '22023';
  end if;

  update public.conversations c
     set name = v_name
   where c.id = p_conversation_id
     and c.kind = 'group'
     and public.is_conversation_participant(p_conversation_id)
     and c.name is distinct from v_name;

  if found then
    perform public.post_system_message(p_conversation_id, v_uid, 'renamed', jsonb_build_object('name', v_name));
  end if;
end;
$$;

create or replace function public.mark_conversation_read(
  p_conversation_id uuid,
  p_read_at timestamptz default null
)
returns timestamptz
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := public.require_user();
  v_at timestamptz := least(coalesce(p_read_at, now()), now());
  v_result timestamptz;
begin
  update public.conversation_participants cp
     set last_read_at = v_at
   where cp.conversation_id = p_conversation_id
     and cp.user_id = v_uid
     and cp.last_read_at < v_at
  returning cp.last_read_at into v_result;

  return v_result;
end;
$$;

create or replace function public.set_conversation_muted(p_conversation_id uuid, p_muted boolean)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := public.require_user();
begin
  update public.conversation_participants cp
     set muted = coalesce(p_muted, false)
   where cp.conversation_id = p_conversation_id and cp.user_id = v_uid;
end;
$$;

-- Messages ───────────────────────────────────────────────────────────────────

create or replace function public.get_messages(
  p_conversation_id uuid,
  p_before_created_at timestamptz default null,
  p_before_id uuid default null,
  p_limit integer default 50
)
returns table (
  id uuid,
  conversation_id uuid,
  sender_id uuid,
  kind public.message_kind,
  body text,
  attachments jsonb,
  meta jsonb,
  reply_to_id uuid,
  edited_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz,
  reactions jsonb,
  reply_to jsonb
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    m.id,
    m.conversation_id,
    m.sender_id,
    m.kind,
    m.body,
    m.attachments,
    m.meta,
    m.reply_to_id,
    m.edited_at,
    m.deleted_at,
    m.created_at,
    coalesce((
      select jsonb_agg(jsonb_build_object('emoji', r.emoji, 'user_id', r.user_id) order by r.created_at)
      from public.message_reactions r
      where r.message_id = m.id
    ), '[]'::jsonb),
    (
      select jsonb_build_object(
        'id', q.id,
        'sender_id', q.sender_id,
        'body', left(q.body, 200),
        'attachment_count', jsonb_array_length(q.attachments),
        'deleted_at', q.deleted_at
      )
      from public.messages q
      where q.id = m.reply_to_id
    )
  from public.messages m
  where m.conversation_id = p_conversation_id
    and (select public.is_conversation_participant(p_conversation_id))
    and (
      p_before_created_at is null
      or (m.created_at, m.id) < (p_before_created_at, coalesce(p_before_id, 'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid))
    )
  order by m.created_at desc, m.id desc
  limit least(greatest(coalesce(p_limit, 50), 1), 100);
$$;

create or replace function public.search_messages(
  p_workspace_id uuid,
  p_query text,
  p_limit integer default 20
)
returns table (
  id uuid,
  conversation_id uuid,
  sender_id uuid,
  body text,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select m.id, m.conversation_id, m.sender_id, m.body, m.created_at
  from public.messages m
  join public.conversation_participants me
    on me.conversation_id = m.conversation_id
   and me.user_id = (select auth.uid())
  join public.conversations c
    on c.id = m.conversation_id
   and c.workspace_id = p_workspace_id
  where char_length(btrim(coalesce(p_query, ''))) >= 2
    and m.kind = 'text'
    and m.deleted_at is null
    and m.body ilike '%' || replace(replace(replace(btrim(p_query), '\', '\\'), '%', '\%'), '_', '\_') || '%'
  order by m.created_at desc
  limit least(greatest(coalesce(p_limit, 20), 1), 50);
$$;

-- ═══════════════════════════════════════════════════════════════════════════
-- 20260913000300_row_level_security.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────────────
-- maeosan · 03 · row level security and privileges
-- Default deny. Clients read what they belong to and write a handful of
-- columns; everything else goes through the RPCs in 02.
-- ─────────────────────────────────────────────────────────────────────────────

alter table public.profiles                  enable row level security;
alter table public.workspaces                enable row level security;
alter table public.workspace_members         enable row level security;
alter table public.invitations               enable row level security;
alter table public.conversations             enable row level security;
alter table public.conversation_participants enable row level security;
alter table public.messages                  enable row level security;
alter table public.message_reactions         enable row level security;

-- Profiles ───────────────────────────────────────────────────────────────────

create policy profiles_select_self_and_teammates
  on public.profiles for select to authenticated
  using (id = (select auth.uid()) or public.shares_workspace_with(id));

create policy profiles_update_self
  on public.profiles for update to authenticated
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));

-- Workspaces ─────────────────────────────────────────────────────────────────

create policy workspaces_select_members
  on public.workspaces for select to authenticated
  using (public.is_workspace_member(id));

create policy workspaces_update_admins
  on public.workspaces for update to authenticated
  using (public.is_workspace_admin(id))
  with check (public.is_workspace_admin(id));

create policy workspace_members_select_members
  on public.workspace_members for select to authenticated
  using (public.is_workspace_member(workspace_id));

-- Invitations: visible to whoever sent them and to admins ────────────────────

create policy invitations_select_inviter_and_admins
  on public.invitations for select to authenticated
  using (invited_by = (select auth.uid()) or public.is_workspace_admin(workspace_id));

-- Conversations ──────────────────────────────────────────────────────────────

create policy conversations_select_participants
  on public.conversations for select to authenticated
  using (public.is_conversation_participant(id));

create policy conversation_participants_select_participants
  on public.conversation_participants for select to authenticated
  using (public.is_conversation_participant(conversation_id));

-- Messages ───────────────────────────────────────────────────────────────────

create policy messages_select_participants
  on public.messages for select to authenticated
  using (public.is_conversation_participant(conversation_id));

create policy messages_insert_own
  on public.messages for insert to authenticated
  with check (
    sender_id = (select auth.uid())
    and kind = 'text'
    and public.is_conversation_participant(conversation_id)
  );

create policy messages_update_own
  on public.messages for update to authenticated
  using (sender_id = (select auth.uid()) and kind = 'text')
  with check (sender_id = (select auth.uid()) and kind = 'text');

create policy message_reactions_select_participants
  on public.message_reactions for select to authenticated
  using (public.is_conversation_participant(conversation_id));

create policy message_reactions_insert_own
  on public.message_reactions for insert to authenticated
  with check (user_id = (select auth.uid()) and public.is_conversation_participant(conversation_id));

create policy message_reactions_delete_own
  on public.message_reactions for delete to authenticated
  using (user_id = (select auth.uid()));

-- Privileges ─────────────────────────────────────────────────────────────────
-- Column-level grants mean a client can never forge sender ids, timestamps,
-- roles or system messages even if a policy were loosened by mistake.

revoke all on all tables in schema public from anon;
revoke insert, update, delete, truncate, references, trigger on all tables in schema public from authenticated;
grant select on all tables in schema public to authenticated;

grant update (full_name, display_name, title, status_text, avatar_path, color, onboarded_at)
  on public.profiles to authenticated;

grant update (name, team_size, use_case, members_can_invite)
  on public.workspaces to authenticated;

grant insert (id, conversation_id, sender_id, body, attachments, reply_to_id)
  on public.messages to authenticated;
grant update (body, deleted_at)
  on public.messages to authenticated;

grant insert (message_id, user_id, emoji)
  on public.message_reactions to authenticated;
grant delete
  on public.message_reactions to authenticated;

-- The invite landing page reads an invitation before the visitor has signed in.
grant execute on function public.get_invitation(text) to anon;

-- ═══════════════════════════════════════════════════════════════════════════
-- 20260913000400_realtime.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────────────
-- maeosan · 04 · realtime
--
-- Topics (all private, authorised by RLS on realtime.messages):
--   user:<uuid>          personal feed. Messages, reactions, read receipts and
--                        conversation changes are fanned out here by the
--                        database, so a client needs exactly one subscription
--                        to keep every chat in the sidebar live.
--   workspace:<uuid>     presence (who is online) and membership/profile hints.
--   conversation:<uuid>  ephemeral typing indicators sent by clients.
-- ─────────────────────────────────────────────────────────────────────────────

create or replace function public.realtime_notify_users(p_user_ids uuid[], p_event text, p_payload jsonb)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid;
begin
  if p_user_ids is null then
    return;
  end if;
  foreach v_user in array p_user_ids loop
    perform realtime.send(p_payload, p_event, 'user:' || v_user::text, true);
  end loop;
end;
$$;

create or replace function public.realtime_notify_workspace(p_workspace_id uuid, p_event text, p_payload jsonb)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform realtime.send(p_payload, p_event, 'workspace:' || p_workspace_id::text, true);
end;
$$;

revoke execute on function public.realtime_notify_users(uuid[], text, jsonb) from public, anon, authenticated;
revoke execute on function public.realtime_notify_workspace(uuid, text, jsonb) from public, anon, authenticated;

-- Messages ───────────────────────────────────────────────────────────────────

create or replace function public.realtime_on_message()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_users uuid[];
  v_payload jsonb;
begin
  if tg_op = 'UPDATE'
    and new.body is not distinct from old.body
    and new.deleted_at is not distinct from old.deleted_at
  then
    return null;
  end if;

  select array_agg(cp.user_id) into v_users
    from public.conversation_participants cp
   where cp.conversation_id = new.conversation_id;

  v_payload := to_jsonb(new);

  if new.reply_to_id is not null then
    v_payload := v_payload || jsonb_build_object('reply_to', (
      select jsonb_build_object(
        'id', q.id,
        'sender_id', q.sender_id,
        'body', left(q.body, 200),
        'attachment_count', jsonb_array_length(q.attachments),
        'deleted_at', q.deleted_at
      )
      from public.messages q
      where q.id = new.reply_to_id
    ));
  end if;

  perform public.realtime_notify_users(
    v_users,
    case tg_op when 'INSERT' then 'message.created' else 'message.updated' end,
    v_payload
  );
  return null;
end;
$$;

create trigger messages_realtime
  after insert or update on public.messages
  for each row execute function public.realtime_on_message();

-- Reactions ──────────────────────────────────────────────────────────────────

create or replace function public.realtime_on_reaction()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row public.message_reactions%rowtype;
  v_users uuid[];
begin
  -- A reaction removed because its message went away is not news. (AFTER
  -- triggers of cascades run at the outer statement level, so pg_trigger_depth
  -- can not tell them apart; the parent row can.)
  if tg_op = 'DELETE' and not exists (select 1 from public.messages m where m.id = old.message_id) then
    return null;
  end if;

  if tg_op = 'DELETE' then
    v_row := old;
  else
    v_row := new;
  end if;

  select array_agg(cp.user_id) into v_users
    from public.conversation_participants cp
   where cp.conversation_id = v_row.conversation_id;

  perform public.realtime_notify_users(
    v_users,
    case tg_op when 'INSERT' then 'reaction.added' else 'reaction.removed' end,
    jsonb_build_object(
      'message_id', v_row.message_id,
      'conversation_id', v_row.conversation_id,
      'user_id', v_row.user_id,
      'emoji', v_row.emoji
    )
  );
  return null;
end;
$$;

create trigger message_reactions_realtime
  after insert or delete on public.message_reactions
  for each row execute function public.realtime_on_reaction();

-- Participants ───────────────────────────────────────────────────────────────
-- Statement level so creating a 20 person group sends 20 events, not 400.

create or replace function public.realtime_on_participants_added()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  r record;
begin
  for r in
    select n.conversation_id, array_agg(cp.user_id) as users
    from (select distinct conversation_id from added_rows) n
    join public.conversation_participants cp on cp.conversation_id = n.conversation_id
    group by n.conversation_id
  loop
    perform public.realtime_notify_users(
      r.users, 'conversation.changed', jsonb_build_object('conversation_id', r.conversation_id)
    );
  end loop;
  return null;
end;
$$;

create trigger conversation_participants_realtime_added
  after insert on public.conversation_participants
  referencing new table as added_rows
  for each statement execute function public.realtime_on_participants_added();

create or replace function public.realtime_on_participants_removed()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  r record;
  v_remaining uuid[];
begin
  -- Conversations deleted outright are announced through workspace.removed.
  for r in
    select rr.conversation_id, array_agg(rr.user_id) as users
    from removed_rows rr
    where exists (select 1 from public.conversations c where c.id = rr.conversation_id)
    group by rr.conversation_id
  loop
    perform public.realtime_notify_users(
      r.users, 'conversation.removed', jsonb_build_object('conversation_id', r.conversation_id)
    );

    select array_agg(cp.user_id) into v_remaining
      from public.conversation_participants cp
     where cp.conversation_id = r.conversation_id;

    perform public.realtime_notify_users(
      v_remaining, 'conversation.changed', jsonb_build_object('conversation_id', r.conversation_id)
    );
  end loop;
  return null;
end;
$$;

create trigger conversation_participants_realtime_removed
  after delete on public.conversation_participants
  referencing old table as removed_rows
  for each statement execute function public.realtime_on_participants_removed();

create or replace function public.realtime_on_participant_updated()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_users uuid[];
begin
  if new.last_read_at is distinct from old.last_read_at then
    select array_agg(cp.user_id) into v_users
      from public.conversation_participants cp
     where cp.conversation_id = new.conversation_id;

    perform public.realtime_notify_users(
      v_users,
      'participant.read',
      jsonb_build_object(
        'conversation_id', new.conversation_id,
        'user_id', new.user_id,
        'last_read_at', new.last_read_at
      )
    );
  end if;

  if new.muted is distinct from old.muted then
    perform public.realtime_notify_users(
      array[new.user_id],
      'conversation.changed',
      jsonb_build_object('conversation_id', new.conversation_id)
    );
  end if;

  return null;
end;
$$;

create trigger conversation_participants_realtime_updated
  after update on public.conversation_participants
  for each row execute function public.realtime_on_participant_updated();

create or replace function public.realtime_on_conversation_renamed()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_users uuid[];
begin
  select array_agg(cp.user_id) into v_users
    from public.conversation_participants cp
   where cp.conversation_id = new.id;

  perform public.realtime_notify_users(
    v_users, 'conversation.changed', jsonb_build_object('conversation_id', new.id)
  );
  return null;
end;
$$;

create trigger conversations_realtime_renamed
  after update of name on public.conversations
  for each row
  when (old.name is distinct from new.name)
  execute function public.realtime_on_conversation_renamed();

-- Workspace membership, profiles and settings ───────────────────────────────
-- Workspace topic payloads are hints only: clients refetch through RLS rather
-- than trusting them, because members may also publish on that topic.

create or replace function public.realtime_on_member_changed()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    perform public.realtime_notify_workspace(
      old.workspace_id, 'member.removed', jsonb_build_object('user_id', old.user_id)
    );
    perform public.realtime_notify_users(
      array[old.user_id], 'workspace.removed', jsonb_build_object('workspace_id', old.workspace_id)
    );
    return null;
  end if;

  perform public.realtime_notify_workspace(
    new.workspace_id, 'member.changed', jsonb_build_object('user_id', new.user_id)
  );
  return null;
end;
$$;

create trigger workspace_members_realtime
  after insert or update or delete on public.workspace_members
  for each row execute function public.realtime_on_member_changed();

create or replace function public.realtime_on_profile_updated()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_workspace uuid;
begin
  for v_workspace in
    select m.workspace_id from public.workspace_members m where m.user_id = new.id
  loop
    perform public.realtime_notify_workspace(
      v_workspace, 'member.changed', jsonb_build_object('user_id', new.id)
    );
  end loop;
  return null;
end;
$$;

create trigger profiles_realtime
  after update on public.profiles
  for each row
  when (
    old.full_name is distinct from new.full_name
    or old.display_name is distinct from new.display_name
    or old.title is distinct from new.title
    or old.status_text is distinct from new.status_text
    or old.avatar_path is distinct from new.avatar_path
    or old.color is distinct from new.color
  )
  execute function public.realtime_on_profile_updated();

create or replace function public.realtime_on_workspace_updated()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform public.realtime_notify_workspace(
    new.id, 'workspace.updated', jsonb_build_object('workspace_id', new.id)
  );
  return null;
end;
$$;

create trigger workspaces_realtime
  after update on public.workspaces
  for each row execute function public.realtime_on_workspace_updated();

-- Channel authorisation ──────────────────────────────────────────────────────

create or replace function public.can_access_realtime_topic(p_topic text)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_scope text := split_part(coalesce(p_topic, ''), ':', 1);
  v_id text := substr(coalesce(p_topic, ''), length(split_part(coalesce(p_topic, ''), ':', 1)) + 2);
begin
  if v_id !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then
    return false;
  end if;

  return case v_scope
    when 'user' then v_id::uuid = (select auth.uid())
    when 'workspace' then public.is_workspace_member(v_id::uuid)
    when 'conversation' then public.is_conversation_participant(v_id::uuid)
    else false
  end;
end;
$$;

drop policy if exists maeosan_realtime_receive on realtime.messages;
create policy maeosan_realtime_receive
  on realtime.messages for select to authenticated
  using (public.can_access_realtime_topic((select realtime.topic())));

-- Clients may publish typing and presence only; personal feeds are written by
-- the database alone, so they cannot be spoofed.
drop policy if exists maeosan_realtime_publish on realtime.messages;
create policy maeosan_realtime_publish
  on realtime.messages for insert to authenticated
  with check (
    realtime.messages.extension in ('broadcast', 'presence')
    and split_part((select realtime.topic()), ':', 1) in ('workspace', 'conversation')
    and public.can_access_realtime_topic((select realtime.topic()))
  );

-- ═══════════════════════════════════════════════════════════════════════════
-- 20260913000500_storage.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────────────
-- maeosan · 05 · storage
--   avatars      public read, object path  <user_id>/<file>
--   attachments  private, object path       <conversation_id>/<user_id>/<file>
-- ─────────────────────────────────────────────────────────────────────────────

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('avatars', 'avatars', true, 2 * 1024 * 1024, array['image/png', 'image/jpeg', 'image/webp', 'image/gif']),
  ('attachments', 'attachments', false, 25 * 1024 * 1024, null)
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.can_access_attachment(p_object_name text)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_conversation text := split_part(coalesce(p_object_name, ''), '/', 1);
begin
  if v_conversation !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then
    return false;
  end if;
  return public.is_conversation_participant(v_conversation::uuid);
end;
$$;

-- Avatars ────────────────────────────────────────────────────────────────────

drop policy if exists avatars_select_own on storage.objects;
create policy avatars_select_own
  on storage.objects for select to authenticated
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text);

drop policy if exists avatars_insert_own on storage.objects;
create policy avatars_insert_own
  on storage.objects for insert to authenticated
  with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text);

drop policy if exists avatars_update_own on storage.objects;
create policy avatars_update_own
  on storage.objects for update to authenticated
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text)
  with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text);

drop policy if exists avatars_delete_own on storage.objects;
create policy avatars_delete_own
  on storage.objects for delete to authenticated
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text);

-- Attachments ────────────────────────────────────────────────────────────────

drop policy if exists attachments_select_participants on storage.objects;
create policy attachments_select_participants
  on storage.objects for select to authenticated
  using (bucket_id = 'attachments' and public.can_access_attachment(name));

drop policy if exists attachments_insert_participants on storage.objects;
create policy attachments_insert_participants
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'attachments'
    and (storage.foldername(name))[2] = (select auth.uid())::text
    and public.can_access_attachment(name)
  );

drop policy if exists attachments_delete_uploader on storage.objects;
create policy attachments_delete_uploader
  on storage.objects for delete to authenticated
  using (bucket_id = 'attachments' and (storage.foldername(name))[2] = (select auth.uid())::text);

-- ═══════════════════════════════════════════════════════════════════════════
-- 20260914000100_platform.sql
-- ═══════════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────────────
-- maeosan · 06 · platform upgrade
--
--   • private schema for internal state, never exposed through the Data API
--   • token-bucket rate limiting for messages, reactions and new groups
--   • message versions + an ordered change feed for gap-free realtime catch-up
--   • ranked full-text message search: prefix matching, trigram similarity and
--     recency decay
--   • presence "last seen", web push subscriptions and push dispatch (pg_net)
--   • admin audit log, nightly housekeeping (pg_cron), health check, indexes
-- ─────────────────────────────────────────────────────────────────────────────

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

-- App configuration ──────────────────────────────────────────────────────────
-- Operator-managed settings read by database code (for example the push
-- dispatch URL and secret). Edit with SQL; see README → Web push.

create table if not exists private.app_config (
  key         text primary key,
  value       text not null,
  updated_at  timestamptz not null default now()
);

-- Shared JSON builders ───────────────────────────────────────────────────────

create or replace function private.reactions_json(p_message_id uuid)
returns jsonb
language sql
stable
set search_path = ''
as $$
  select coalesce(
    jsonb_agg(jsonb_build_object('emoji', r.emoji, 'user_id', r.user_id) order by r.created_at),
    '[]'::jsonb
  )
  from public.message_reactions r
  where r.message_id = p_message_id;
$$;

create or replace function private.reply_preview_json(p_message_id uuid)
returns jsonb
language sql
stable
set search_path = ''
as $$
  select jsonb_build_object(
    'id', q.id,
    'sender_id', q.sender_id,
    'body', left(q.body, 200),
    'attachment_count', jsonb_array_length(q.attachments),
    'deleted_at', q.deleted_at
  )
  from public.messages q
  where q.id = p_message_id;
$$;

-- Rate limiting: token bucket ────────────────────────────────────────────────
-- Each (user, bucket) holds up to `capacity` tokens refilled continuously at
-- `refill_per_second`. Bursts are allowed, sustained floods are not. On refusal
-- the error carries `retry_after=<seconds>` in its hint so clients back off
-- precisely instead of guessing.

create table if not exists private.rate_limits (
  user_id      uuid not null,
  bucket       text not null,
  tokens       double precision not null,
  refilled_at  timestamptz not null,
  primary key (user_id, bucket)
);

create or replace function private.consume_rate_limit(
  p_user_id uuid,
  p_bucket text,
  p_capacity integer,
  p_refill_per_second double precision,
  p_cost integer default 1
)
returns void
language plpgsql
set search_path = ''
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_tokens double precision;
  v_refilled timestamptz;
  v_retry_after integer;
begin
  if p_user_id is null then
    return;
  end if;

  insert into private.rate_limits (user_id, bucket, tokens, refilled_at)
  values (p_user_id, p_bucket, p_capacity, v_now)
  on conflict (user_id, bucket) do nothing;

  select r.tokens, r.refilled_at
    into v_tokens, v_refilled
    from private.rate_limits r
   where r.user_id = p_user_id and r.bucket = p_bucket
   for update;

  v_tokens := least(
    p_capacity::double precision,
    v_tokens + greatest(0, extract(epoch from (v_now - v_refilled))) * p_refill_per_second
  );

  if v_tokens < p_cost then
    v_retry_after := greatest(1, ceil((p_cost - v_tokens) / p_refill_per_second))::integer;
    raise exception 'You''re sending a lot at once. Try again in a few seconds.'
      using errcode = 'P0429', hint = 'retry_after=' || v_retry_after;
  end if;

  update private.rate_limits r
     set tokens = v_tokens - p_cost,
         refilled_at = v_now
   where r.user_id = p_user_id and r.bucket = p_bucket;
end;
$$;

revoke execute on function private.consume_rate_limit(uuid, text, integer, double precision, integer) from public, anon, authenticated;

-- Messages: versions, change feed, search vector ─────────────────────────────

alter table public.messages
  add column if not exists version integer not null default 1,
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists search_vector tsvector
    generated always as (to_tsvector('simple'::regconfig, coalesce(body, ''))) stored;

create index if not exists messages_search_vector_idx on public.messages using gin (search_vector);
create index if not exists messages_changes_idx on public.messages (conversation_id, updated_at, id);
create index if not exists messages_unread_idx
  on public.messages (conversation_id, created_at)
  where kind = 'text' and deleted_at is null;

-- Security definer so it can consult private.* (rate limits). It still pins
-- every column a client must not control.
create or replace function public.messages_before_write()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_attachment jsonb;
  v_prefix text;
begin
  if tg_op = 'INSERT' then
    new.created_at := now();
    new.updated_at := new.created_at;
    new.version := 1;
    new.edited_at := null;
    new.deleted_at := null;
    new.body := btrim(new.body, E' \t\r\n');

    if new.reply_to_id is not null and not exists (
      select 1 from public.messages r
      where r.id = new.reply_to_id and r.conversation_id = new.conversation_id
    ) then
      raise exception 'You can only reply to messages in the same conversation.' using errcode = '22023';
    end if;

    if new.kind = 'text' then
      perform private.consume_rate_limit(new.sender_id, 'message', 30, 1.0);

      v_prefix := new.conversation_id::text || '/' || new.sender_id::text || '/';
      for v_attachment in select value from jsonb_array_elements(new.attachments) loop
        if jsonb_typeof(v_attachment) <> 'object'
          or left(coalesce(v_attachment ->> 'path', ''), length(v_prefix)) <> v_prefix
          or coalesce(v_attachment ->> 'name', '') = ''
        then
          raise exception 'One of the attachments is invalid.' using errcode = '22023';
        end if;
      end loop;
    end if;

    return new;
  end if;

  -- Only foreign keys (ON DELETE SET NULL for a deleted account or message)
  -- change these columns; clients hold no privilege on them.
  if new.sender_id is distinct from old.sender_id or new.reply_to_id is distinct from old.reply_to_id then
    return new;
  end if;

  if old.deleted_at is not null then
    raise exception 'This message was deleted.' using errcode = '22023';
  end if;

  new.id := old.id;
  new.conversation_id := old.conversation_id;
  new.sender_id := old.sender_id;
  new.kind := old.kind;
  new.meta := old.meta;
  new.reply_to_id := old.reply_to_id;
  new.created_at := old.created_at;
  new.version := old.version + 1;
  new.updated_at := now();

  if new.deleted_at is not null then
    new.deleted_at := now();
    new.body := '';
    new.attachments := '[]'::jsonb;
    new.edited_at := old.edited_at;
    return new;
  end if;

  new.attachments := old.attachments;
  if new.body is distinct from old.body then
    new.body := btrim(new.body, E' \t\r\n');
    new.edited_at := now();
  else
    new.edited_at := old.edited_at;
  end if;

  return new;
end;
$$;

create or replace function public.message_reactions_before_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  select m.conversation_id
    into new.conversation_id
    from public.messages m
   where m.id = new.message_id
     and m.kind = 'text'
     and m.deleted_at is null;

  if new.conversation_id is null then
    raise exception 'That message no longer exists.' using errcode = '22023';
  end if;

  perform private.consume_rate_limit(new.user_id, 'reaction', 40, 2.0);
  new.created_at := now();
  return new;
end;
$$;

-- A reaction change bumps the message version so the change feed carries it.
create or replace function public.message_reactions_touch_message()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_message_id uuid;
begin
  if tg_op = 'DELETE' then
    -- When the message itself is gone (a cascade) the update below matches nothing.
    v_message_id := old.message_id;
  else
    v_message_id := new.message_id;
  end if;

  update public.messages m
     set updated_at = now()
   where m.id = v_message_id and m.deleted_at is null;
  return null;
end;
$$;

drop trigger if exists message_reactions_touch_message on public.message_reactions;
create trigger message_reactions_touch_message
  after insert or delete on public.message_reactions
  for each row execute function public.message_reactions_touch_message();

-- Realtime payloads never need the search vector.
create or replace function public.realtime_on_message()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_users uuid[];
  v_payload jsonb;
begin
  if tg_op = 'UPDATE'
    and new.body is not distinct from old.body
    and new.deleted_at is not distinct from old.deleted_at
  then
    return null;
  end if;

  select array_agg(cp.user_id) into v_users
    from public.conversation_participants cp
   where cp.conversation_id = new.conversation_id;

  v_payload := to_jsonb(new) - 'search_vector';
  if new.reply_to_id is not null then
    v_payload := v_payload || jsonb_build_object('reply_to', private.reply_preview_json(new.reply_to_id));
  end if;

  perform public.realtime_notify_users(
    v_users,
    case tg_op when 'INSERT' then 'message.created' else 'message.updated' end,
    v_payload
  );
  return null;
end;
$$;

drop function if exists public.get_messages(uuid, timestamptz, uuid, integer);

create function public.get_messages(
  p_conversation_id uuid,
  p_before_created_at timestamptz default null,
  p_before_id uuid default null,
  p_limit integer default 50
)
returns table (
  id uuid,
  conversation_id uuid,
  sender_id uuid,
  kind public.message_kind,
  body text,
  attachments jsonb,
  meta jsonb,
  reply_to_id uuid,
  edited_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz,
  updated_at timestamptz,
  version integer,
  reactions jsonb,
  reply_to jsonb
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    m.id, m.conversation_id, m.sender_id, m.kind, m.body, m.attachments, m.meta, m.reply_to_id,
    m.edited_at, m.deleted_at, m.created_at, m.updated_at, m.version,
    private.reactions_json(m.id),
    case when m.reply_to_id is null then null else private.reply_preview_json(m.reply_to_id) end
  from public.messages m
  where m.conversation_id = p_conversation_id
    and (select public.is_conversation_participant(p_conversation_id))
    and (
      p_before_created_at is null
      or (m.created_at, m.id) < (p_before_created_at, coalesce(p_before_id, 'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid))
    )
  order by m.created_at desc, m.id desc
  limit least(greatest(coalesce(p_limit, 50), 1), 100);
$$;

-- Everything that changed in a conversation after a cursor, oldest change
-- first. Clients page with (updated_at, id) until a short page comes back.
create or replace function public.get_message_changes(
  p_conversation_id uuid,
  p_since timestamptz,
  p_since_id uuid default null,
  p_limit integer default 200
)
returns table (
  id uuid,
  conversation_id uuid,
  sender_id uuid,
  kind public.message_kind,
  body text,
  attachments jsonb,
  meta jsonb,
  reply_to_id uuid,
  edited_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz,
  updated_at timestamptz,
  version integer,
  reactions jsonb,
  reply_to jsonb
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    m.id, m.conversation_id, m.sender_id, m.kind, m.body, m.attachments, m.meta, m.reply_to_id,
    m.edited_at, m.deleted_at, m.created_at, m.updated_at, m.version,
    private.reactions_json(m.id),
    case when m.reply_to_id is null then null else private.reply_preview_json(m.reply_to_id) end
  from public.messages m
  where m.conversation_id = p_conversation_id
    and (select public.is_conversation_participant(p_conversation_id))
    and (m.updated_at, m.id) > (p_since, coalesce(p_since_id, '00000000-0000-0000-0000-000000000000'::uuid))
  order by m.updated_at, m.id
  limit least(greatest(coalesce(p_limit, 200), 1), 500);
$$;

-- Ranked search ──────────────────────────────────────────────────────────────
-- score = (2 · cover density rank of prefix terms + trigram similarity
--          + substring bonus) · (0.35 + 0.65 · e^(−age_days / 45))
-- so the best textual match wins, but recent conversations float up.

drop function if exists public.search_messages(uuid, text, integer);

create function public.search_messages(
  p_workspace_id uuid,
  p_query text,
  p_limit integer default 20
)
returns table (
  id uuid,
  conversation_id uuid,
  sender_id uuid,
  body text,
  created_at timestamptz,
  rank real
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_query text := btrim(coalesce(p_query, ''));
  v_tsquery tsquery;
  v_like text;
begin
  if char_length(v_query) < 2 then
    return;
  end if;

  select to_tsquery('simple'::regconfig, string_agg(quote_literal(word) || ':*', ' & '))
    into v_tsquery
    from regexp_split_to_table(lower(v_query), '[^[:alnum:]]+') as word
   where word <> '';

  v_like := '%' || replace(replace(replace(v_query, '\', '\\'), '%', '\%'), '_', '\_') || '%';

  return query
  select
    m.id,
    m.conversation_id,
    m.sender_id,
    m.body,
    m.created_at,
    (
      (
        case when v_tsquery is not null and m.search_vector @@ v_tsquery
          then ts_rank_cd(m.search_vector, v_tsquery, 32) * 2
          else 0
        end
        + extensions.similarity(m.body, v_query)
        + case when m.body ilike v_like then 0.25 else 0 end
      )
      * (0.35 + 0.65 * exp(-extract(epoch from (now() - m.created_at)) / (86400.0 * 45)))
    )::real
  from public.messages m
  join public.conversation_participants me
    on me.conversation_id = m.conversation_id
   and me.user_id = (select auth.uid())
  join public.conversations c
    on c.id = m.conversation_id
   and c.workspace_id = p_workspace_id
  where m.kind = 'text'
    and m.deleted_at is null
    and ((v_tsquery is not null and m.search_vector @@ v_tsquery) or m.body ilike v_like)
  order by 6 desc, 5 desc
  limit least(greatest(coalesce(p_limit, 20), 1), 50);
end;
$$;

-- Groups: creation is rate limited ───────────────────────────────────────────

create or replace function public.create_group_conversation(
  p_workspace_id uuid,
  p_member_ids uuid[],
  p_name text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := public.require_user();
  v_members uuid[];
  v_name text := nullif(btrim(coalesce(p_name, '')), '');
  v_id uuid;
begin
  if not public.is_workspace_member(p_workspace_id) then
    raise exception 'Workspace not found.' using errcode = '42501';
  end if;

  perform private.consume_rate_limit(v_uid, 'group', 10, 0.05);

  select coalesce(array_agg(distinct x), '{}')
    into v_members
    from unnest(coalesce(p_member_ids, '{}'::uuid[])) as x
   where x <> v_uid;

  if coalesce(array_length(v_members, 1), 0) = 0 then
    raise exception 'Pick at least one person.' using errcode = '22023';
  end if;
  if array_length(v_members, 1) > 99 then
    raise exception 'Group chats can have up to 100 people.' using errcode = '22023';
  end if;
  if exists (
    select 1 from unnest(v_members) as x
    where not exists (
      select 1 from public.workspace_members m
      where m.workspace_id = p_workspace_id and m.user_id = x
    )
  ) then
    raise exception 'Some of those people are not in this workspace.' using errcode = '22023';
  end if;

  insert into public.conversations (workspace_id, kind, name, created_by)
  values (p_workspace_id, 'group', v_name, v_uid)
  returning id into v_id;

  insert into public.conversation_participants (conversation_id, user_id)
  select v_id, x from unnest(array_append(v_members, v_uid)) as x;

  perform public.post_system_message(v_id, v_uid, 'group_created', jsonb_build_object('name', v_name));
  return v_id;
end;
$$;

-- Presence: last seen ────────────────────────────────────────────────────────

alter table public.profiles add column if not exists last_seen_at timestamptz;

-- Called by clients as a heartbeat; writes at most once every 45 seconds.
create or replace function public.touch_presence()
returns void
language sql
security definer
set search_path = ''
as $$
  update public.profiles p
     set last_seen_at = now()
   where p.id = (select auth.uid())
     and (p.last_seen_at is null or p.last_seen_at < now() - interval '45 seconds');
$$;

drop function if exists public.list_workspace_members(uuid, uuid);

create function public.list_workspace_members(
  p_workspace_id uuid,
  p_user_id uuid default null
)
returns table (
  user_id uuid,
  role public.workspace_role,
  joined_at timestamptz,
  email text,
  full_name text,
  display_name text,
  title text,
  status_text text,
  avatar_path text,
  color text,
  last_seen_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    m.user_id, m.role, m.joined_at, p.email, p.full_name, p.display_name, p.title,
    p.status_text, p.avatar_path, p.color, p.last_seen_at
  from public.workspace_members m
  join public.profiles p on p.id = m.user_id
  where m.workspace_id = p_workspace_id
    and (p_user_id is null or m.user_id = p_user_id)
    and (select public.is_workspace_member(p_workspace_id))
  order by lower(coalesce(p.display_name, p.full_name, p.email));
$$;

-- Web push ───────────────────────────────────────────────────────────────────

create table if not exists public.push_subscriptions (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references public.profiles (id) on delete cascade,
  endpoint      text not null unique check (endpoint ~ '^https://' and char_length(endpoint) <= 1024),
  p256dh        text not null check (char_length(p256dh) <= 256),
  auth          text not null check (char_length(auth) <= 128),
  user_agent    text check (user_agent is null or char_length(user_agent) <= 300),
  created_at    timestamptz not null default now(),
  last_used_at  timestamptz not null default now()
);

create index if not exists push_subscriptions_user_idx on public.push_subscriptions (user_id, last_used_at desc);

alter table public.push_subscriptions enable row level security;

drop policy if exists push_subscriptions_select_own on public.push_subscriptions;
create policy push_subscriptions_select_own
  on public.push_subscriptions for select to authenticated
  using (user_id = (select auth.uid()));

revoke all on public.push_subscriptions from anon;
revoke insert, update, delete, truncate, references, trigger on public.push_subscriptions from authenticated;

create or replace function public.save_push_subscription(
  p_endpoint text,
  p_p256dh text,
  p_auth text,
  p_user_agent text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := public.require_user();
begin
  if coalesce(p_endpoint, '') !~ '^https://' then
    raise exception 'That push subscription is not valid.' using errcode = '22023';
  end if;

  -- An endpoint belongs to one browser profile; whoever signs in there owns it.
  insert into public.push_subscriptions (user_id, endpoint, p256dh, auth, user_agent)
  values (v_uid, p_endpoint, p_p256dh, p_auth, left(p_user_agent, 300))
  on conflict (endpoint) do update
    set user_id = excluded.user_id,
        p256dh = excluded.p256dh,
        auth = excluded.auth,
        user_agent = excluded.user_agent,
        last_used_at = now();

  -- Keep each person's ten most recently used devices.
  delete from public.push_subscriptions s
   where s.user_id = v_uid
     and s.id not in (
       select s2.id from public.push_subscriptions s2
       where s2.user_id = v_uid
       order by s2.last_used_at desc
       limit 10
     );
end;
$$;

create or replace function public.delete_push_subscription(p_endpoint text)
returns void
language sql
security definer
set search_path = ''
as $$
  delete from public.push_subscriptions s
   where s.endpoint = p_endpoint and s.user_id = (select auth.uid());
$$;

do $$
begin
  create extension if not exists pg_net with schema extensions;
exception
  when others then
    raise notice 'pg_net is unavailable (%); web push dispatch stays off.', sqlerrm;
end;
$$;

-- After a text message commits, ask the app to fan out push notifications.
-- pg_net queues the request and sends it asynchronously, so sending a message
-- never waits on the network and a rolled-back insert sends nothing.
create or replace function private.dispatch_push()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_url text;
  v_secret text;
begin
  if new.kind <> 'text' then
    return null;
  end if;

  select c.value into v_url from private.app_config c where c.key = 'push_dispatch_url';
  select c.value into v_secret from private.app_config c where c.key = 'push_dispatch_secret';
  if v_url is null or v_secret is null then
    return null;
  end if;

  begin
    perform net.http_post(
      url := v_url,
      body := jsonb_build_object('message_id', new.id, 'conversation_id', new.conversation_id),
      headers := jsonb_build_object('Content-Type', 'application/json', 'Authorization', 'Bearer ' || v_secret),
      timeout_milliseconds := 5000
    );
  exception
    when others then
      raise warning 'maeosan push dispatch skipped: %', sqlerrm;
  end;

  return null;
end;
$$;

drop trigger if exists messages_push_dispatch on public.messages;
create trigger messages_push_dispatch
  after insert on public.messages
  for each row execute function private.dispatch_push();

-- Audit log ──────────────────────────────────────────────────────────────────

create table if not exists public.audit_events (
  id            bigint generated always as identity primary key,
  workspace_id  uuid not null references public.workspaces (id) on delete cascade,
  actor_id      uuid references public.profiles (id) on delete set null,
  action        text not null check (char_length(action) <= 60),
  target_id     uuid,
  metadata      jsonb not null default '{}'::jsonb,
  created_at    timestamptz not null default now()
);

create index if not exists audit_events_workspace_idx on public.audit_events (workspace_id, created_at desc);

alter table public.audit_events enable row level security;

drop policy if exists audit_events_select_admins on public.audit_events;
create policy audit_events_select_admins
  on public.audit_events for select to authenticated
  using (public.is_workspace_admin(workspace_id));

revoke all on public.audit_events from anon;
revoke insert, update, delete, truncate, references, trigger on public.audit_events from authenticated;

create or replace function private.record_audit(
  p_workspace_id uuid,
  p_action text,
  p_target_id uuid,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language sql
set search_path = ''
as $$
  insert into public.audit_events (workspace_id, actor_id, action, target_id, metadata)
  values (p_workspace_id, (select auth.uid()), p_action, p_target_id, coalesce(p_metadata, '{}'::jsonb));
$$;

create or replace function private.audit_workspace_members()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    perform private.record_audit(new.workspace_id, 'member.joined', new.user_id, jsonb_build_object('role', new.role));
  elsif tg_op = 'UPDATE' then
    if new.role is distinct from old.role then
      perform private.record_audit(
        new.workspace_id, 'member.role_changed', new.user_id,
        jsonb_build_object('from', old.role, 'to', new.role)
      );
    end if;
  -- Deleting the workspace itself cascades here; there is nothing left to log to.
  elsif exists (select 1 from public.workspaces w where w.id = old.workspace_id) then
    perform private.record_audit(old.workspace_id, 'member.removed', old.user_id, jsonb_build_object('role', old.role));
  end if;
  return null;
end;
$$;

drop trigger if exists workspace_members_audit on public.workspace_members;
create trigger workspace_members_audit
  after insert or update or delete on public.workspace_members
  for each row execute function private.audit_workspace_members();

create or replace function private.audit_invitations()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    perform private.record_audit(new.workspace_id, 'invitation.created', new.id, jsonb_build_object('email', new.email, 'role', new.role));
  elsif new.status is distinct from old.status then
    perform private.record_audit(new.workspace_id, 'invitation.' || new.status::text, new.id, jsonb_build_object('email', new.email));
  end if;
  return null;
end;
$$;

drop trigger if exists invitations_audit on public.invitations;
create trigger invitations_audit
  after insert or update on public.invitations
  for each row execute function private.audit_invitations();

create or replace function private.audit_workspaces()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_changes jsonb := '{}'::jsonb;
begin
  if new.name is distinct from old.name then
    v_changes := v_changes || jsonb_build_object('name', jsonb_build_array(old.name, new.name));
  end if;
  if new.team_size is distinct from old.team_size then
    v_changes := v_changes || jsonb_build_object('team_size', jsonb_build_array(old.team_size, new.team_size));
  end if;
  if new.use_case is distinct from old.use_case then
    v_changes := v_changes || jsonb_build_object('use_case', jsonb_build_array(old.use_case, new.use_case));
  end if;
  if new.members_can_invite is distinct from old.members_can_invite then
    v_changes := v_changes || jsonb_build_object('members_can_invite', jsonb_build_array(old.members_can_invite, new.members_can_invite));
  end if;

  if v_changes <> '{}'::jsonb then
    perform private.record_audit(new.id, 'workspace.updated', new.id, v_changes);
  end if;
  return null;
end;
$$;

drop trigger if exists workspaces_audit on public.workspaces;
create trigger workspaces_audit
  after update on public.workspaces
  for each row execute function private.audit_workspaces();

-- Housekeeping ───────────────────────────────────────────────────────────────

create or replace function private.run_housekeeping()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_rate_limits integer;
  v_invitations integer;
  v_push integer;
  v_audit integer;
begin
  delete from private.rate_limits r where r.refilled_at < now() - interval '1 day';
  get diagnostics v_rate_limits = row_count;

  delete from public.invitations i
   where (i.status = 'revoked' and i.created_at < now() - interval '90 days')
      or (i.status = 'pending' and i.expires_at < now() - interval '90 days');
  get diagnostics v_invitations = row_count;

  delete from public.push_subscriptions s where s.last_used_at < now() - interval '120 days';
  get diagnostics v_push = row_count;

  delete from public.audit_events a where a.created_at < now() - interval '400 days';
  get diagnostics v_audit = row_count;

  return jsonb_build_object(
    'rate_limits', v_rate_limits,
    'invitations', v_invitations,
    'push_subscriptions', v_push,
    'audit_events', v_audit
  );
end;
$$;

do $$
begin
  create extension if not exists pg_cron;
  perform cron.schedule('maeosan-housekeeping', '17 3 * * *', 'select private.run_housekeeping()');
exception
  when others then
    raise notice 'pg_cron is unavailable (%); run private.run_housekeeping() on your own schedule.', sqlerrm;
end;
$$;

-- Health check ───────────────────────────────────────────────────────────────

create or replace function public.health_check()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object('ok', true, 'time', now(), 'schema', 6);
$$;

grant execute on function public.health_check() to anon, authenticated;

notify pgrst, 'reload schema';
