// Bundles supabase/migrations/*.sql, in order, into supabase/schema.sql: one
// file that can be pasted into the Supabase SQL Editor.
//   npm run db:bundle

import { readdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const root = new URL("../supabase/", import.meta.url);
const migrationsDir = new URL("migrations/", root);
const rule = "-- " + "═".repeat(75);

const files = (await readdir(migrationsDir)).filter((name) => name.endsWith(".sql")).sort();
if (files.length === 0) throw new Error("No migrations found in supabase/migrations.");

const sections = await Promise.all(
  files.map(async (name) => {
    const sql = (await readFile(new URL(name, migrationsDir), "utf8")).trimEnd();
    return `\n${rule}\n-- ${name}\n${rule}\n\n${sql}\n`;
  }),
);

const header = [
  "-- maeosan · complete database schema (generated by `npm run db:bundle`, do not edit)",
  "-- Supabase → SQL Editor → New query → paste this whole file → Run.",
  "-- On a project that already has other tables, run supabase/reset.sql first.",
  "",
  "notify pgrst, 'reload schema';",
  "",
].join("\n");

const output = `${header}${sections.join("")}\nnotify pgrst, 'reload schema';\n`;
const target = new URL("schema.sql", root);
await writeFile(target, output);

console.log(`Bundled ${files.length} migrations into ${fileURLToPath(target)} (${output.split("\n").length} lines).`);
